#!/usr/bin/env bash
set -eu

SINGLESTORE_IMAGE_TAGS=(
    "alma-8.0.19-f48780d261-4.0.11-1.16.0"
    "alma-8.1.32-e3d3cde6da-4.0.16-1.17.6"
    "alma-8.5.22-fe61f40cd1-4.1.0-1.17.11"
    "alma-8.7.12-483e5f8acb-4.1.0-1.17.15"
)
SINGLESTORE_IMAGE_TAGS_COUNT=${#SINGLESTORE_IMAGE_TAGS[@]}
SPARK_VERSIONS=(
    "3.5.0"
    "3.4.2"
    "3.3.4"
    "3.2.4"
    "3.1.3"
)
SPARK_VERSIONS_COUNT=${#SPARK_VERSIONS[@]}

TEST_NUM=${SPLIT:-"0"}

SINGLESTORE_IMAGE_TAG_INDEX=$(( $TEST_NUM / $SPARK_VERSIONS_COUNT))
SINGLESTORE_IMAGE_TAG_INDEX=$((SINGLESTORE_IMAGE_TAG_INDEX>=SINGLESTORE_IMAGE_TAGS_COUNT ? SINGLESTORE_IMAGE_TAGS_COUNT-1 : SINGLESTORE_IMAGE_TAG_INDEX))
SINGLESTORE_IMAGE_TAG=${SINGLESTORE_IMAGE_TAGS[SINGLESTORE_IMAGE_TAG_INDEX]}

SPARK_VERSION_INDEX=$(( $TEST_NUM % $SPARK_VERSIONS_COUNT))
SPARK_VERSION=${SPARK_VERSIONS[SPARK_VERSION_INDEX]}

if [ $TEST_NUM == $(($SINGLESTORE_IMAGE_TAGS_COUNT*$SPARK_VERSIONS_COUNT)) ]
then
  echo 'export FORCE_READ_FROM_LEAVES=TRUE'
else
  echo 'export FORCE_READ_FROM_LEAVES=FALSE'
fi

echo "export SINGLESTORE_IMAGE='singlestore/cluster-in-a-box:$SINGLESTORE_IMAGE_TAG'"
echo "export SPARK_VERSION='$SPARK_VERSION'"
echo "export TEST_FILTER='testOnly -- -l  ExcludeFromSpark${SPARK_VERSION:0:1}${SPARK_VERSION:2:1}'"
echo "export SCALA_VERSION='2.12.12'"
